version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_eemi_class
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Example health check
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    container_name: flask_app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy  # Wait until MySQL service is healthy
    volumes:
      - .:/app

volumes:
  db_data:
